name: Deploy to EC2 on Aws

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t smartdeliveri_api .

    - name: push image
      run:  docker push smartdelivery_api

   
